import { ELang } from '../../enums/ELang.ts';
import { sergeiTelegramChatId } from '../../telegramBot/secret.ts';
import { TPersonalConfig } from '../../types/TPersonalConfig.ts';

const sergeiConfig: TPersonalConfig = {
  regions: [
    {
      name: 'European Union',
      link: 'https://www.linkedin.com/jobs/search/?f_AL=true&f_JT=F&f_TPR=r86400&f_WT=1%2C3&geoId=91000000&keywords=software%20developer&location=European%20Union&sortBy=DD',
    },
    // remote, cyprus, georgia
  ],
  keywords: ['javascript', 'typescript', 'node', 'react', 'russia'],
  excludeWords: [
    'junior',
    'automation',
    'python',
    'php',
    'architect',
    'graduate',
    'angular',
    'devops',
    'bangkok',
    'ios',
    'android',
    'uae national',
    'reliability',
    'magento',
    'product manager',
    'talend',
    'assistant',
    'mobile',
    'algorithm',
    'rides',
    'native',
    'hardware',
    'oracle',
    'technician',
    'field service',
    'infrastructure',
    'metaverse',
    'game developer',
    'blockchain',
    'technical',
    'security',
    'freelance',
    'java',
    'bsw platform',
    'firmware',
    'devsecops',
    'qa manual',
    'network',
    'sales',
    'commerce',
    'service engineer',
    'autosar',
    '(ml)',
    'system',
    'dynamics engineer',
    'kafka engineer',
    'mendix',
    'account manager',
    'arabic',
    ' ai ',
    'ingegnere',
    'post-doctoral',
    'drupal',
    'test engineer',
    'cloud engineer',
    'c++',
    'embedded ',
    ' seo ',
    'dutch speaking',
    'wordpress',
    'italian',
  ],
  telegramChatId: sergeiTelegramChatId,
  lang: ELang.EN,
  storageFileName: 'sergeiStorage.json',
};

export { sergeiConfig };
